{% set version = "1.2.1" %}
# library version is different from project version
# Check 'meson.build' upstream in every release!
{% set so_name = "6.9.0" %}
{% set so_name_major = so_name.split('.')[0] %}

package:
  name: dav1d-split
  version: {{ version }}

source:
  url: https://code.videolan.org/videolan/dav1d/-/archive/{{ version }}/dav1d-{{ version }}.tar.gz
  sha256: 2dd85860d213479672b1c708e31593446e8c2b53ff41e2ca25a2eafb718424e2

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - meson >=0.49
    - ninja
    - nasm >=2.14
    - pkg-config

outputs:

  # Everything needed to build against libdav1d (excludes binary)
  - name: dav1d-dev
    script: install.py
    build:
      run_exports:
        - {{ pin_subpackage('libdav1d' ~ so_name_major) }}
    requirements:
      build:
        - {{ compiler('c') }}
      run:
        - {{ pin_subpackage('libdav1d' ~ so_name_major, exact=True) }}        # [unix]
    test:
      commands:
      # Need these things
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}                       # [unix]
        - test -f ${PREFIX}/lib/libdav1d.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\lib\\dav1d.lib exit 1               # [win]
        - test -f ${PREFIX}/include/dav1d/dav1d.h                             # [unix]
        - if not exist %PREFIX%\\Library\\include\\dav1d\\dav1d.h exit 1      # [win]
        - test -f ${PREFIX}/lib/pkgconfig/dav1d.pc                            # [unix]
        - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\dav1d.pc exit 1     # [win]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libdav1d.a                                  # [unix]
        - if exist %PREFIX%\\Library\\bin\\dav1d.dll exit 1                   # [win]
        - test ! -f ${PREFIX}/bin/dav1d                                       # [unix]
        - if exist %PREFIX%\\Library\\bin\\dav1d exit 1                       # [win]

  # Everything needed to run the dav1d binary
  - name: dav1d
    script: install.py
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - {{ pin_subpackage('dav1d-dev', exact=True) }}
      run:
        - {{ pin_subpackage('libdav1d' ~ so_name_major) }}
    test:
      commands:
      # Need these things
        - dav1d -v
        - test -f ${PREFIX}/lib/libdav1d.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\bin\\dav1d.dll exit 1               # [win]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\dav1d.lib exit 1                   # [win]
        - test ! -f ${PREFIX}/include/dav1d/dav1d.h                           # [unix]
        - if exist %PREFIX%\\Library\\include\\dav1d\\dav1d.h exit 1          # [win]
        - test ! -f ${PREFIX}/lib/pkgconfig/dav1d.pc                          # [unix]
        - if exist %PREFIX%\\Library\\lib\\pkgconfig\\dav1d.pc exit 1         # [win]

  # Only what's needed for run_exports downstream
  - name: libdav1d{{ so_name_major }}
    script: install.py
    build:
      run_exports:
        - {{ pin_subpackage('libdav1d' ~ so_name_major) }}
    requirements:
      build:
        - {{ compiler('c') }}
      run:
        - {{ pin_subpackage('_libdav1d_api', max_pin='x.x.x') }}              # [win]
    test:
      commands:
      # Need these things
        - test -f ${PREFIX}/lib/libdav1d.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\bin\\dav1d.dll exit 1               # [win]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libdav1d.{{ so_name }}{{ SHLIB_EXT }}       # [osx]
        - test ! -f ${PREFIX}/bin/dav1d                                       # [unix]
        - if exist %PREFIX%\\Library\\bin\\dav1d exit 1                       # [win]
        - test ! -f ${PREFIX}/lib/libdav1d{{ SHLIB_EXT }}                     # [unix]
        - if exist %PREFIX%\\Library\\lib\\dav1d.lib exit 1                   # [win]
        - test ! -f ${PREFIX}/include/dav1d/dav1d.h                           # [unix]
        - if exist %PREFIX%\\Library\\include\\dav1d\\dav1d.h exit 1          # [win]
        - test ! -f ${PREFIX}/lib/pkgconfig/dav1d.pc                          # [unix]
        - if exist %PREFIX%\\Library\\lib\\pkgconfig\\dav1d.pc exit 1         # [win]

  # Clobber preventer for Windows; prevents multiple dav1d.dll files from being
  # installed simultaneously. This lets us avoid exporting a strict pin on the
  # libdav1d API which is not strictly correlated with the ABI.
  - name: _libdav1d_api
    build:
      skip: true  # [not win]
    about:
      summary: >
        An empty package that prevents multiple ABIs of libdavid
        being installed simultaneously on Windows.

about:
  home: https://code.videolan.org/videolan/dav1d
  summary: dav1d is the fastest AV1 decoder on all platforms
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING

extra:
  feedstock-name: dav1d
  recipe-maintainers:
    - carterbox
    - jaimergp
